### 관련 사이트
https://m.blog.naver.com/dnjswns2280/221605723329

### 데이터 사이언스 
https://datascienceschool.net/01%20python/03.01%20%EB%84%98%ED%8C%8C%EC%9D%B4%20%EB%B0%B0%EC%97%B4.html

In [12]:
#리스트에서 배열 만들기
import numpy as np

# 리스트에서 배열 만들기
arr = np.array([1, 4, 2, 5, 3])
print(arr)

arr = np.array([3.14, 4, 2, 3])
print(arr)

arr = np.array([1, 2, 3, 4], dtype =  'float32') # 넘파이에서는 데이타 타입을 지정해 줄수 있음
print(arr)


[1 4 2 5 3]
[3.14 4.   2.   3.  ]
[1. 2. 3. 4.]


In [28]:
# 처음부터 배열 만들기
arr = np.zeros(10, dtype = int) #0으로 채운 배열 생성
print(arr)

arr = np.ones((3, 5), dtype = float) #1로 채운 배열 생성
print(arr)

arr = np.full((3,5), 3.14) # 3.14로 채운 배열 만들기 
print(arr)

arr = np.arange(0, 20, 2) # 0에서 시작해 2씩 더해 20까지 채우는 배열 생성
print(arr)

arr = np.linspace(0, 1, 5) # 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
print(arr)

arr = np.random.random((3,3)) # 3*3 크기의 난수 배열 생성
print(arr)

np.random.normal(0, 1, (3, 3)) # 평균 0, 표준 편차 1의 정규 분포를 따르는 3*3 난수 배열
np.random.randint(0, 10, (3, 3)) # [0, 10) 구간의 임의로 정수로 채운 3*3 배열 만들기
#np.eye(3) # 크기 3의 단위 행렬 만들기


[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.9882611  0.91433377 0.78142526]
 [0.95433582 0.98832947 0.77471066]
 [0.64357433 0.55566827 0.26328806]]


array([[1, 2, 4],
       [7, 4, 7],
       [9, 2, 5]])

In [14]:
#배열 속성을 지정 하여 보자
#배열 속성 확인하기

x = np.random.randint(10, size = (3, 4, 5), dtype = 'int8') 
x 
x.ndim # 3
x.shape # (3, 4, 5)
x.size # 60 = 3 * 4* 5
x.dtype # int8

dtype('int8')

In [24]:
#배열 인덱싱 - 읽는 방법

x1 = np.random.randint(10, size = 6)
x1
x2 = np.random.randint(10, size = (3, 4))
x2
x3 = np.random.randint(10, size = (3, 4, 5))
x3

x1[0] # 양수 인덱스 (맨 앞 요소)
x1[3] # 세 번째 요소 
x1[-1] # 음수 인덱스 (맨 뒤 요소)
x1[-4] # 뒤에서 네 번째 요소 

x2[2, 0] # 2행 0열 (리스트 인덱스와 비교)
# list[i][j] / ndarray[i, j]
x3[1, 2, 3] # 1차원, 2행, 3열 요소

x2[0, 0] = 15 # x2의 0행 0열 값을 15로 바꿈